### PR TITLE
Version 3.1.0

### PR DESCRIPTION
**Pull request by aleswita**
## Change log
- change some classes names
	- **NasExt\Forms\Controls\DependentSelectBoxData** to **NasExt\Forms\DependentData** (**not** BC break, library have compatibility bridge)
	- **NasExt\Forms\DI\DependentSelectBoxExtension** to **NasExt\Forms\DependentExtension** (**not** BC break, library have compatibility bridge)

- new control **NasExt\Forms\Controls\DependentMultiSelectBox** for multi select box
	- inherit from Nette\Forms\Controls\MultiSelectBox

- changes in NasExt\Forms\Controls\DependentSelectBox
	- can not set callback in constructor (**BC break**)
	- can not set as multiple select box (**BC break**)
	- parens not set as array, but set as variable ends arguments (...$parents) (**BC break**)
	- properly set disabled control and disabled items
	- you can set dependent prompt value

- global
	- tests (coverage 98%)
	- Nette Coding Standard

## Nastaveni testu
- Travis CI, aby se sputily testy pri kazdem pull requestu/commitu atd., je treba v nastaveni GitHubu pridat Travis CI servis
	- vedle odkazu na Wiki u repozitare je **Settings** -> Installed GitHub Apps -> Add service -> Travis CI
	- na strance https://travis-ci.org se prihlas pres GitHub ucet a na profilu https://travis-ci.org/profile/NasExt zaskrtni NasExt/DependentSelectBox
- Coverals, pro procentualni zobrazeni pokryti kodu testem
	- na strance https://coveralls.io se prihlas pres GitHub ucet a strance s repozitaremi https://coveralls.io/repos/new zasrtni NasExt/DependentSelectBox

### CODE REVIEW

**Comment by duskohu** [comment]
Paradna praca, testy som este nerobil ani tu konfiguraciu, takze velka pomoc, dakujem.
Vsetko som nakonfiguroval ako si pisal, len sa mi nezda ci je vsetko ok, kedze tie ikonky su sede.

**Comment by aleswita** [comment]
Jakmile releasnes novou verzi, tak se ty testy spusti a az dojednou do konci, tak se ty ikonky zmeni.

**Comment by duskohu** [comment]
Ok dik, pridam ti admin prava na toto repo, urobil si dost prace, takze ked budes nieco potrebovat kludne mozez, len mi daj prosim vediet.

**Comment by aleswita** [comment]
Jasan a diky.

**Pull request merged**
